version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: lepsi-nez-a-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lepsi_nez_a
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lepsi-nez-a-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/lepsi_nez_a
      RUST_LOG: lepsi_nez_a_backend=debug,tower_http=debug,sqlx=info
    ports:
      - "6767:6767"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
